// <auto-generated />
using System;
using Flowforge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowforge.Migrations
{
    [DbContext(typeof(FlowforgeDbContext))]
    [Migration("20260125150434_AddRevisionSnapshotsAndScheduler")]
    partial class AddRevisionSnapshotsAndScheduler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Flowforge.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<int>("SystemBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemBlockId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Flowforge.Models.BlockConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetBlockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceBlockId");

                    b.HasIndex("TargetBlockId");

                    b.ToTable("BlockConnections");
                });

            modelBuilder.Entity("Flowforge.Models.SystemBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Start block",
                            Type = "Start"
                        },
                        new
                        {
                            Id = 2,
                            Description = "End block",
                            Type = "End"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Calculation block",
                            Type = "Calculation"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Conditional block",
                            Type = "If"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Switch (case) block",
                            Type = "Switch"
                        },
                        new
                        {
                            Id = 6,
                            Description = "HTTP request block",
                            Type = "HttpRequest"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Parser JSON/XML",
                            Type = "Parser"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Loop block",
                            Type = "Loop"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Wait (delay) block",
                            Type = "Wait"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Transform text casing",
                            Type = "TextTransform"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Replace text (literal or regex)",
                            Type = "TextReplace"
                        });
                });

            modelBuilder.Entity("Flowforge.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRevisionId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputData")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultData")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowRevisions");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkflowRevisionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowRevisionId");

                    b.ToTable("WorkflowSchedules");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowVariables");
                });

            modelBuilder.Entity("Flowforge.Models.Block", b =>
                {
                    b.HasOne("Flowforge.Models.SystemBlock", "SystemBlock")
                        .WithMany("Blocks")
                        .HasForeignKey("SystemBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowforge.Models.Workflow", "Workflow")
                        .WithMany("Blocks")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemBlock");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Flowforge.Models.BlockConnection", b =>
                {
                    b.HasOne("Flowforge.Models.Block", "SourceBlock")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flowforge.Models.Block", "TargetBlock")
                        .WithMany("TargetConnections")
                        .HasForeignKey("TargetBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceBlock");

                    b.Navigation("TargetBlock");
                });

            modelBuilder.Entity("Flowforge.Models.Workflow", b =>
                {
                    b.HasOne("Flowforge.Models.WorkflowRevision", "CurrentRevision")
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentRevision");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowExecution", b =>
                {
                    b.HasOne("Flowforge.Models.Workflow", "Workflow")
                        .WithMany("WorkflowExecutions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowRevision", b =>
                {
                    b.HasOne("Flowforge.Models.Workflow", "Workflow")
                        .WithMany("WorkflowRevisions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowSchedule", b =>
                {
                    b.HasOne("Flowforge.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flowforge.Models.WorkflowRevision", "WorkflowRevision")
                        .WithMany()
                        .HasForeignKey("WorkflowRevisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowRevision");
                });

            modelBuilder.Entity("Flowforge.Models.WorkflowVariable", b =>
                {
                    b.HasOne("Flowforge.Models.Workflow", "Workflow")
                        .WithMany("WorkflowVariables")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Flowforge.Models.Block", b =>
                {
                    b.Navigation("SourceConnections");

                    b.Navigation("TargetConnections");
                });

            modelBuilder.Entity("Flowforge.Models.SystemBlock", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Flowforge.Models.Workflow", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("WorkflowExecutions");

                    b.Navigation("WorkflowRevisions");

                    b.Navigation("WorkflowVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
